Repository KojinKuro/ludole, pull requests merged in 2024-05, with the labels that each got.

#8 Generate a the same random number based on a key entered and a range
  docs/pull_request_template.md
  package-lock.json
  package.json
  src/javascript/generate.js
Labels: enhancement, good first issue

#10 Created mockup page
  public/mario.webp
  src/App.css
  src/App.jsx
  src/index.css
Labels: enhancement

#13 Feature/image rendering
  src/ImageRender/ImageRender.css
  src/ImageRender/ImageRender.jsx
Labels: enhancement

#15 Create functioning game
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/GameStatus.css
  src/GameStatus.jsx
  src/Guesses.css
  src/ImageRender/ImageRender.css
  src/ImageRender/ImageRender.jsx
  src/assets/react.svg
  src/components/Game/Game.css
  src/components/Game/Game.jsx
  src/components/GameStatus/GameStatus.css
  src/components/GameStatus/GameStatus.jsx
  src/components/Guesses/Guesses.css
  src/components/Guesses/Guesses.jsx
  src/components/ImageBlur/ImageBlur.css
  src/components/ImageBlur/ImageBlur.jsx
  src/javascript/game.js
  src/javascript/generate.js
  src/javascript/guess.js
  src/main.jsx
  src/mockGames.js
Labels: enhancement

#18 Complete React Router + Game Autocomplete Search
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/GameStatus/GameStatus.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchResult.css
  src/components/SearchBar/SearchResult.jsx
  src/javascript/guess.js
  src/main.jsx
  src/pages/AboutPage.jsx
  src/pages/GamePage.css
  src/pages/GamePage.jsx
  src/pages/InstructionPage.jsx
Labels: enhancement

#22 Testing/cypress
  cypress/e2e/routing.cy.js
  cypress/e2e/spec.cy.js
Labels: testing

#28 Allow manual setting of answer
  cypress/e2e/routing.cy.js
  cypress/e2e/spec.cy.js
  src/App.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/GamePage.jsx
Labels: bug, enhancement

#31 Testing/cypress
  cypress/e2e/addGame.cy.js
  cypress/e2e/routing.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/game.json
  src/App.jsx
  src/javascript/apiCalls.js
  src/pages/AboutPage.jsx
Labels: testing
